<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_FileAttachment</name>
   <tag></tag>
   <elementGuidId>bfa43b50-1f1d-4bbd-a5ef-0c1775322f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//b[contains(@class,'VizExFileAttachment__FileName')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
